# --------------------------------------------------------------- # 
# Custom Script /Step Framework  - Relaxed NG Compact Schema
# Used to document the input/output/layout of Ingenium steps.
#
# Some users may find XML to be a more convient way to specify 
# custom scripts/steps due to comments and built in validation.
# 
# Use the apps/ProjConfigCreateUpdateCS.py to read the xml, compute the 
# uuid (based on full path of the script) and the hash of the underlying code.
#
# --------------------------------------------------------------- #

datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"
namespace rng = "http://relaxng.org/ns/structure/1.0"

start = custom-scripts-def

input-types-def = "INT"                | 
                  "STRING"             | 
                  "FLOAT"              | 
                  "ENUM"               | 
                  "DATA_PATH"          | 
                  "TIME"               | 
                  "BOOL"               |
                  "FLIGHT_COMMAND"     | # Provides command builder lookup and autocompletes based on stem and selected dictionary
                  "SIM_COMMAND"        | # Autocompletes based on stem and selected dictionary
                  "FLIGHT_EVR"         | # Autocompletes based on ID and selected dictionary (will auto-populate NAME field on entry if present)
                  "FLIGHT_TELEM"       | # Autocompletes based on ID and selected dictionary (will auto-populate NAME field on entry if present)
                  "SIM_EVR"            | # Autocompletes based on NAME and selected dictionary (will auto-populate ID field on entry if present)
                  "SIM_TELEM"          | # Autocompletes based on ID and selected dictionary (will auto-populate NAME field on entry if present)
                  "VERIFICATION_COND"    # Array of Verification Condition and 0-2 Verification Values (depending on Condition) 

    output-types-def = "INT" | 
                       "STRING" | 
                       "FLOAT"  |
                       "FILE"   |  # Provides a link to an uploaded file 
                       "IMAGE"  |  # Displays an Image with the step
                       "SERIES"    # Provides an interactive graph based on time series data


custom-scripts-def = element custom-scripts {
    # Header
    header-def,
    # Custom Scripts
    custom-script-def+
}
    

header-def = element header {
    # Name of the project/mission generating or using the dictionary
    attribute mission_name { xsd:token }
}

custom-script-def = element custom_script {
  # The script name. Must be posix compliant
  attribute script_name {text},
  # Whether the custom script is considered a "command"
  # Used to control automatic execution
  # Recommended to be flagged true if script is commanding the vehicle or simualtion under test
  attribute is_command {"true" | "false"},  
  # Description of the script. What does it do?
  attribute description {text},
  # SHA256 hash of the script
  attribute hash {text},
  # Script Path. The local path to the script
  attribute script_path {text},
  # Script ID (Base64 encoding of path)
  attribute script_id {text}?,
  # List of inputs the script takes
  input-field-def*,
  # Entries are (possibly) repeating structure that has inputs, outputs, and an associated stauts
  # If defined they require at least one to be populated
  # Only one entry can be defined per step.
  script-entry-def?,
  # List of output fields the script produces
  output-field-def*,
  # Output array
  output-array-def?,
  # Advanced formatting. Note that if this is selected it must be defined for all fields.
  advanced-layout-def?
 }
 
output-array-def = element output_array {
    # Maximum number of elements in array (use 0 to specify no limit)
    attribute max_entries {xsd:nonNegativeInteger},
    # Name of the array of ouputs
    attribute name {name_format},
    # How the table/array is described in the ui (if not provided will use variable name)
    attribute display_name {xsd:token}?,
    # Description of the output array
    attribute description {text},    
    # Identify each input field in the entry
    output-array-field-def+
}

input-field-def = element input_field {
    # The name of the input (the "key")
    # Must be unique within a script
    attribute name {name_format},
    # How the field is described in the ui (if not provided will use variable name)
    attribute display_name {xsd:token}?,
    # Description of the input field
    attribute description {text},
    # Whether the script input is an authoring or execution phase input. Execution phase inputs 
    # are entered manually during execution. Authoring phase inputs are developed ahead of time and are under CM.
    attribute phase {"AUTHORING" | "EXECUTION"},
    # Whether the input is required or optional
    attribute required {"YES" | "NO"},
    # Type of the argument. Note that that there are special "Ingenium types" which will cause Ingenium to
    # accept multiple formats and or do variable substitution. The type also impacts the layout/UI.
    attribute type {input-types-def},
    # Default input value
    # Will be used to pre-populate the input field if provided
    # Note should be value for the type defined above and the enumerations defined below
    attribute default_value {string}?,
    # List of enumeration values (required for type == "ENUM"
    element enumeration {
        # List of allowable values for the enumeration 
        element enum {attribute symbolic {name_format}, 
                      attribute numeric {xsd:integer}?}+
    }?
    }

output-field-def = element output_field {
    # Definition of a single custom script output
    # Used to provide type validation and proper display format
    # The name of the input (the "key")
    # Must be unique within a script
    attribute name {name_format},
    # How the field is displayed in the ui (if not provided will use field name)
    # Note that this is ignored if the advanced layout is populated
    attribute display_name {xsd:token}?,
    # Description of the output field
    attribute description {text},
    # Type of output
    attribute type {output-types-def}
}

output-array-field-def = element output_array_field {
    # Definition of a single custom script output array
    # Used to provide type validation and proper display format
    
    # The name of the input (the "key")
    # Must be unique within a script
    attribute name {name_format},
    # How the field is displayed in the ui (if not provided will use field name)
    # Note that this is ignored if the advanced layout is populated
    attribute display_name {xsd:token}?,
    # Description of the output field
    attribute description {text},
    # Type of output
    attribute type {output-types-def},
    # Visible in the array table (or just in details)
    # Note that this is ignored if the advanced layout is populated
    attribute visible {"YES" | "NO"}?
}

script-entry-def = element script_entry {
    # An entry is a repeating section of identical inputs/outputs, each with its own dedicated pass/fail status.
    # Entrys can be added/removed but at least one must be specified
    
    # One or more inputs 
    input-field-def+,
    
    # Zero or more outputs

    # List of output fields the script produces
    output-field-def*,
    
    # Output array
    output-array-def?,
    
    # Display Value - this is the output value that will be display 
    # Must match the name of one of the output fields
    # Note that this is ignored if the advanced layout is populated
    attribute display_value {name_format}?
}

name_format = xsd:token

# Advanced format
# This invokes the advanced formatting options available for Ingenium Custom Scripts.
# If this option is selected - all defined fields must have formatting defined here.

columns-def = xsd:positiveInteger { maxInclusive="12"}


advanced-layout-def = element advanced_layout {
    (section-layout-def | entry-section-layout-def)+
}
section-layout-def = element section {
    section-header-def?,
    section-content-def?,
    section-results-def?
}

entry-section-layout-def = element entry_section {
    section-header-def?,
    section-content-def?,
    section-results-def?
}

section-header-def = element section_header {
    (layout-display-def | input-layout-field-def | output-layout-field-def | icon-def)+
}

section-content-def = element section_content {
    (layout-display-def | input-layout-field-def | output-layout-field-def | icon-def | image-display-def)+
}

section-results-def = element section_results {
    (layout-display-def | output-layout-field-def | icon-def | image-display-def | table-def | series-def)+
}

# This is a formatted string that can display multiple variables embedded in a string.
# Note that content here is read only and inputs mush be captured in another field
# Also note that this could have no variables embedded and function as a standalone string.
layout-display-def = element layout_display {
    # A formatted string using python style f"" formating 
    # E.g. "The {criminals} were no match for {superhero}"
    # The parameters in the string should correspond to defined input/output fields
    template-def,
    # Optionally can have a mouseover.
    mouseover-display-def?,
    # Layout which will position the display within the section element
    layout-def
}
# The only distinction between input and output layout field information is the types of fields 
# they can display and where they are used in the layout. 
input-layout-field-def = layout-field-def
output-layout-field-def = layout-field-def

layout-field-def = element layout_field {
    # The variable to display (must match a field defined in custom script)
    attribute field_name {name_format},
    
    label-def,
        
    # Tool Tip
    # Optional hover text to display input assistence / help
    attribute tool_tip {xsd:token}?,
    
    # Layout which will position the field within the section element
    layout-def
}

icon-def = element icon {
    # Icon Type Status maps to step or entry pass/fail/error status (check/X)
    # Icon Type Details is an "eye icon" 
    attribute icon_type {"STATUS" | "DETAILS"},
    mouseover-display-def?,
    layout-def
}

# Will display when user mouses over either the step/entry pass fail indication or the table "details" icon
mouseover-display-def = element mouseover_display {
    element mouseover_element {attribute field_name {name_format}, attribute display_name {xsd:string}?}+
}

layout-def = element layout {
    # Veritical position of the field in the UI, expressed as "rows" (starting at 1) 
    attribute row {xsd:positiveInteger},
    # Horizontal position of the field in the UI, expressed as "columns" (starting at 1 max of 12) 
    attribute column {columns-def},
    # Nominal width of a field
    # This is expressed as "columns" or increments of 1/12 of available screen widths
    attribute width {columns-def},
    # Nominal height of a field (in rows)
    attribute height {xsd:integer},
    # Alignment (within column)
    attribute align {"LEFT" | "CENTER" | "RIGHT"}
}

label-def = element label {
    attribute label_content {xsd:string},
    attribute label_loc {"LEFT" | "RIGHT" | "TOP" | "BOTTOM"},
    attribute label_align {"LEFT" | "RIGHT" | "CENTER" }
}

# This will display an image (scaled to fit the layout)
# This allows for multiple images to be returned
image-display-def = element image_display {
    # The variable to display (must match an image output field defined)
    attribute field_name {name_format},
    label-def,
    layout-def
}

# This will display time series data (scaled to fit the layout)
# This allows for multiple images to be returned
series-def = element series {
    # The variable to display (must match an series output field defined)
    attribute field_name {name_format},

    # The label to use 
    label-def,
    
    # Where to place the series in the section
    layout-def
}

table-def = element table {
    # Table to display (note needs to coorespond with a output_array_field field
    attribute table_name {name_format},
    
    label-def,
    
    # Nominal height of a field  (Units are in "rows") 
    attribute row_height {xsd:integer}?,    
    
    # The final element in any table is (optionally) a "Display" icon with a mouseover 
    mouseover-display-def?,
    
    # Fields to display and their width (in columns)
    # Note that the display name of each field will be used to indicate the column
    table-column-def+
}

table-column-def = element table_field {
    # Nominal width of the field in the table (starting at 1 max of 12)
    # This is expressed as "columns" or increments of 1/12 of available screen widths
    attribute width {columns-def},
    # The Column header definition
    attribute column_label {xsd:string},
    # A formatted display for the content using elements of output_array_field
    template-def 
}


template-def = element template {
    # A formatted string using python style f"" formating 
    # E.g. "The {criminals} were no match for {superhero}"
    # The parameters in the string should correspond to defined input/output fields
    attribute template {xsd:string}
}



